<?php 
require_once(__DIR__.'/theme-settings.php');
require_once(__DIR__.'/nav_menu.php');
require_once(__DIR__.'/translate.php');
require_once(__DIR__.'/scripts.php');
require_once(__DIR__.'/action.php');
require_once(__DIR__.'/post_type.php');
require_once(__DIR__.'/shortcode.php');
require_once(__DIR__.'/buttons_editor.php');
require_once(__DIR__.'/privat24.php');
require_once(__DIR__.'/wp-ajax.php');
require_once(__DIR__.'/admin/admin-init.php');
require_once(__DIR__.'/create_tables.php');
require_once(__DIR__ . '/classes/BLOrder.php');
require_once(__DIR__ . '/classes/BLReminder.php');
require_once(__DIR__ . '/classes/BLService.php');
require_once(__DIR__ . '/classes/BoklagDB.php');
require_once(__DIR__ . '/classes/CreditCard.php');
require_once(__DIR__ . '/classes/BLNotification.php');
require_once(__DIR__ . '/classes/BLFriend.php');
require_once(__DIR__ . '/classes/BLEmployment.php');
require_once(__DIR__ . '/classes/BLComments.php');
require_once(__DIR__ . '/classes/BLPerfomers.php');
